controller_list:
  - name: fake_ee_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
initial:  # Define initial robot poses.
  - group: ee_group
    pose: transport_opse